site_name: Design ex Machina

theme:
  name: material
  palette:
    scheme: dem
  custom_dir: config/overrides
  features:
    - content.code.annotate
    - navigation.tabs
  icon:
    admonition:
      info: octicons/info-16
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  language: en

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.mark
  - pymdownx.extra
  - attr_list

extra_css:
  - assets/stylesheets/extra.css
  - style.css

extra_javascript: 
  - docs/js/logo-redirect.js

plugins:
  - search


nav:
    - Home: index.md
    - The course:
      - Introduction: course/00intro.md
      - Getting Started: course/gettingStarted.md
      - Working on the canvas: course/canvas.md
      - Loops and Conditionals: course/loopsConds.md
      - Interactive visuals: course/interaction.md
      - Integrating AI: course/integratingAI.md
      - Further resources: course/resources.md
    - The workshop:
      - The workshop: workshop/overview.md
    - Documentation: book.md