site_name: Design ex Machina

theme:
  name: material
  palette:
    scheme: dem
  custom_dir: config/overrides
  features:
    - content.code.annotate
    - navigation.tabs
  icon:
    admonition:
      info: octicons/info-16
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  language: en

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.mark
  - pymdownx.extra
  - attr_list

extra_css:
  - assets/stylesheets/extra.css
  - style.css

extra_javascript: 
  - docs/js/logo-redirect.js

plugins:
  - search


nav:
    - Home: index.md
    - The course:
      - Introduction: course/00intro.md
      - Getting Started: course/01gettingStarted.md
      - Loops and Conditionals: course/02loopsConds.md
      - Interaction: course/03interaction.md
      - Integrating AI: course/04integratingAI.md
    - The workshop:
      - Overview: workshop/overview.md
    - Documentation:
      - Documentation: documentation/book.md
    - About me:
      - About me: me/aboutme.md